/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paint;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Point;
import java.lang.reflect.Constructor;
import java.lang.reflect.Method;
import java.net.URL;
import java.net.URLClassLoader;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import javax.swing.Box;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author HP-
 */
public class NewJFrame extends javax.swing.JFrame {
    
    /*public class parser {
    public void read(){
        File f = new File("input.txt");
        try {
            Scanner in =new Scanner(f);
            while(in.hasNext()){
            if (in.next()=="rectangle") ((MyCanvas)jPanel2).addShape(new Rectangle());
            else if (in.next()=="circle") ((MyCanvas)jPanel2).addShape(new Circle());
            else if (in.next()=="Oval") ((MyCanvas)jPanel2).addShape(new Oval());
            else if (in.next()=="Triangle") ((MyCanvas)jPanel2).addShape(new Triangle());
            }
        }
        catch(FileNotFoundException e ){}
    }
    
    public void refresh(){
        ((MyCanvas)jPanel2).shapes=new ArrayList<>();
        read();
    }
}*/
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        jButton21.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel2 = new MyCanvas();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Rectangle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton2.setText("Circle");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setToolTipText("Select the Item you want to edit");
        jComboBox1.setAutoscrolls(true);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Colour");

        jButton5.setBackground(new java.awt.Color(0, 204, 0));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 0, 204));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("^");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton8.setText("V");
        jButton8.setToolTipText("");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jButton9.setText(">");
        jButton9.setMaximumSize(new java.awt.Dimension(47, 31));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton10.setText("<");
        jButton10.setMaximumSize(new java.awt.Dimension(45, 31));
        jButton10.setMinimumSize(new java.awt.Dimension(45, 31));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel2.setText("Move");

        jButton11.setText("Oval");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Triangle");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Line Segment");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("Square");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton15.setText("Redo");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton16.setText("Undo");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setToolTipText("");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel3.setDoubleBuffered(true);

        jButton17.setText("Copy");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setText("Load Shape");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setText("Remove");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setText("Edit");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setText("Add Your Ugly Shape");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6)
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(6, 6, 6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton7)
                                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(6, 6, 6)
                                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(5, 5, 5))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton19))
                            .addGap(9, 9, 9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton13)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton21)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton13)
                            .addGap(6, 6, 6)
                            .addComponent(jButton1))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton12)
                            .addGap(6, 6, 6)
                            .addComponent(jButton2))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton14)
                            .addGap(6, 6, 6)
                            .addComponent(jButton11))
                        .addComponent(jButton21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(16, 16, 16)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addGap(11, 11, 11)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton17)
                            .addComponent(jButton18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton19)
                            .addComponent(jButton20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        undoneItems=new ArrayList<>();
        MyCanvas panel=(MyCanvas)jPanel2;
        panel.unDoneShapes= new ArrayList<>();
        jLabel3.setText("");
        Circle r = new Circle();
        
        counter++;
        jComboBox1.addItem("Circle "+counter);
        panel.addShape(r);
        jComboBox1.setSelectedIndex(counter-1);
        jButton20ActionPerformed(evt);
        jComboBox1.repaint();       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jLabel3.setText("");
        int i=jComboBox1.getSelectedIndex();
        MyCanvas canvas=(MyCanvas)jPanel2;
        canvas.shapes.get(i).setColor(Color.BLACK);        
        jPanel2.repaint();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code /here:
        jLabel3.setText("");
        int i=jComboBox1.getSelectedIndex();
        MyCanvas canvas=(MyCanvas)jPanel2;
        canvas.shapes.get(i).setColor(Color.RED);
        jPanel2.repaint();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jLabel3.setText("");
        int i=jComboBox1.getSelectedIndex();
        MyCanvas canvas=(MyCanvas)jPanel2;
        canvas.shapes.get(i).setColor(Color.GREEN);
        jPanel2.repaint();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        //jLabel3.setText("");
        int i=jComboBox1.getSelectedIndex();
        MyCanvas canvas=(MyCanvas)jPanel2;
        canvas.shapes.get(i).setColor(Color.BLUE);
        jPanel2.repaint();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jLabel3.setText("");
        int i=jComboBox1.getSelectedIndex();
        MyCanvas canvas=(MyCanvas)jPanel2;
        Point position=canvas.shapes.get(i).getPosition();
        canvas.shapes.get(i).setPosition(new Point(position.x,position.y-10));
        jPanel2.repaint();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        jLabel3.setText("");
        int i=jComboBox1.getSelectedIndex();
        MyCanvas canvas=(MyCanvas)jPanel2;
        Point position=canvas.shapes.get(i).getPosition();
        canvas.shapes.get(i).setPosition(new Point(position.x+10,position.y));
        jPanel2.repaint();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        jLabel3.setText("");
        int i=jComboBox1.getSelectedIndex();
        MyCanvas canvas=(MyCanvas)jPanel2;
        Point position=canvas.shapes.get(i).getPosition();
        canvas.shapes.get(i).setPosition(new Point(position.x-10,position.y));
        jPanel2.repaint();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        jLabel3.setText("");
        int i=jComboBox1.getSelectedIndex();
        MyCanvas canvas=(MyCanvas)jPanel2;
        Point position=canvas.shapes.get(i).getPosition();
        canvas.shapes.get(i).setPosition(new Point(position.x,position.y+10));
        jPanel2.repaint();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        undoneItems=new ArrayList<>();
        MyCanvas panel=(MyCanvas)jPanel2;
        panel.unDoneShapes= new ArrayList<>();
        jLabel3.setText("");
        Oval r = new Oval();
        
        counter++;
        jComboBox1.addItem("Oval "+counter);
        panel.addShape(r);
        jComboBox1.setSelectedIndex(counter-1);
        jButton20ActionPerformed(evt);        
        jComboBox1.repaint(); 
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        undoneItems=new ArrayList<>();
        MyCanvas panel=(MyCanvas)jPanel2;
        panel.unDoneShapes= new ArrayList<>();
        jLabel3.setText("");
        Rectangle r = new Rectangle(); 
        
        counter++;
        jComboBox1.addItem("Rectangle "+counter);
        panel.addShape(r);
        jComboBox1.setSelectedIndex(counter-1);
        jButton20ActionPerformed(evt);
        jComboBox1.repaint();        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        undoneItems=new ArrayList<>();
        MyCanvas panel=(MyCanvas)jPanel2;
        panel.unDoneShapes= new ArrayList<>();
        jLabel3.setText("");
        Triangle r = new Triangle();
        
        counter++;
        jComboBox1.addItem("Triangle "+counter);
        panel.addShape(r);
        jComboBox1.setSelectedIndex(counter-1);
        jButton20ActionPerformed(evt);
        jComboBox1.repaint();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        undoneItems=new ArrayList<>();
        MyCanvas panel=(MyCanvas)jPanel2;
        panel.unDoneShapes= new ArrayList<>();
        jLabel3.setText("");
        Line r = new Line();
        
        counter++;
        jComboBox1.addItem("Line Segment "+counter);        
        panel.addShape(r);
        jComboBox1.setSelectedIndex(counter-1);
        jButton20ActionPerformed(evt);
        jComboBox1.repaint();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        undoneItems=new ArrayList<>();
        MyCanvas panel=(MyCanvas)jPanel2;
        panel.unDoneShapes= new ArrayList<>();
        jLabel3.setText("");
        Square r = new Square();
        
        counter++;
        jComboBox1.addItem("Square "+counter);
        
        panel.addShape(r);
        jComboBox1.setSelectedIndex(counter-1);
        jButton20ActionPerformed(evt);
        jComboBox1.repaint();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        MyCanvas panel=(MyCanvas)jPanel2;
        if(panel.shapes.isEmpty()) {
            jLabel3.setText("Nothing to undo");            
            return;
        }
        --counter;
        int i =((((MyCanvas)jPanel2)).shapes.size()-1);
        if(undoneItems.size()>=20) undoneItems.remove(0);
        undoneItems.add(this.jComboBox1.getItemAt(i));
        jComboBox1.removeItemAt(i);
        jLabel3.setText("");
        panel.undo();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        MyCanvas panel=(MyCanvas)jPanel2;
        if(panel.unDoneShapes.isEmpty()) {
            jLabel3.setText("Nothing to redo");
            return;
        }
        String s = undoneItems.get(undoneItems.size()-1);
        undoneItems.remove(undoneItems.size()-1);
        s=s.substring(0, s.length()-1);
        s=s+(++counter);
                
        jComboBox1.addItem(s);
        jLabel3.setText("");
        jComboBox1.setSelectedIndex(counter-1);        
        panel.redo();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        MyCanvas panel=(MyCanvas)jPanel2;
        int i=jComboBox1.getSelectedIndex();
        try{
            Shape s = (Shape)panel.shapes.get(i).clone();
            Point position = s.getPosition();
            s.setPosition(new Point(position.x+10,position.y-10));
            panel.addShape(s);
            String name=this.jComboBox1.getItemAt(i);
            name=name.substring(0,name.length()-1);
            counter++;
            
            
            jComboBox1.addItem(name+counter);
            jComboBox1.setSelectedIndex(counter-1);
        }catch(CloneNotSupportedException CloneNotSupportedException){
            
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
         JFileChooser f = new JFileChooser();
         f.setFileSelectionMode(JFileChooser.FILES_ONLY); 
         f.showSaveDialog(null);
         
         if(f.getSelectedFile()==null) return;
        try{
            
            String inputValue = JOptionPane.showInputDialog("Please input the name of your class");
            this.jLabel3.setText(""+f.getSelectedFile());
            String stringPath= java.net.URLEncoder.encode(f.getSelectedFile().toString(),"UTF-8");
            //String inputValue="RoundRectangle";
            
            URL path = f.getSelectedFile().toURI().toURL();
            this.jLabel3.setText("URL created");
            URL[] paths={path}; 
            URLClassLoader child = new URLClassLoader(paths, this.getClass().getClassLoader());            
            this.jLabel3.setText("Loaded");
            Class<?> classToLoad = Class.forName ("paint."+inputValue, true, child);
            
            MyCanvas panel = (MyCanvas) this.jPanel2;
            panel.installPluginShape(((Class<? extends Shape>)classToLoad));
            jButton21.setVisible(true);
        }catch(Exception e ){this.jLabel3.setText(e.toString());}
            //this.jLabel3.setText("Plugin Loaded");*/
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        MyCanvas panel=(MyCanvas)jPanel2;
        if(counter==0) {this.jLabel3.setText("Nothing to Remove");return;}
        counter--;
        int i=this.jComboBox1.getSelectedIndex();
        panel.removeShape(panel.shapes.get(i));       
        jComboBox1.removeItemAt(i);
        jLabel3.setText("");
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        int i=jComboBox1.getSelectedIndex();
        MyCanvas canvas=(MyCanvas)jPanel2;
        HashMap<String,Double> properties =  (HashMap<String,Double>) canvas.shapes.get(i).getProperties();
        Set set = properties.entrySet();      
        // Get an iterator
        Iterator iterator = set.iterator();
        int result;
        
        JPanel myPanel = new JPanel();
        Point p =  canvas.shapes.get(i).getPosition(); 
        myPanel.add(new JLabel("X"));
        JTextField xField = new JTextField(5);
        xField.setText(""+p.getX());
        myPanel.add(xField);        
        myPanel.add(new JLabel("Y"));        
        JTextField yField = new JTextField(5);
        yField.setText(""+p.getY());
        myPanel.add(yField);
        ArrayList<Object> panelObjects= new ArrayList<>();
        // Display elements
         while(iterator.hasNext()) {
            Map.Entry me = (Map.Entry)iterator.next();
            panelObjects.add(new JLabel((String)me.getKey()));
            myPanel.add((JLabel)panelObjects.get(panelObjects.size()-1));
            JTextField newField = new JTextField(5);
             panelObjects.add(newField);
            myPanel.add((JTextField)panelObjects.get(panelObjects.size()-1));
            newField.setText(""+me.getValue());
            /*System.out.print(me.getKey() + ": ");
            System.out.println(me.getValue());*/
        }
        
        
       
        result = JOptionPane.showConfirmDialog(null, myPanel, 
               "Please Enter Values", JOptionPane.OK_CANCEL_OPTION);
        if(result==JOptionPane.OK_OPTION){            
            try{
                double x=Double.parseDouble(xField.getText());
                double y=Double.parseDouble(yField.getText());
                canvas.shapes.get(i).setPosition(new Point((int)x,(int)y));
            for(int n=0;n<panelObjects.size();n++){
                
                JLabel label= (JLabel)panelObjects.get(n);
                String key= label.getText();
                JTextField txtField= (JTextField)panelObjects.get(++n);
                double value = Double.parseDouble(txtField.getText());
                properties.put(key,value);
                
            }
            canvas.shapes.get(i).setProperties(properties);
            canvas.repaint();
            }catch(Exception e){
                
                System.out.println(e.toString());
                jLabel3.setText("Invalid Input");
            }
                
            }
            
            /*width=Integer.parseInt(widthField.getText());
            height=Integer.parseInt(lengthField.getText());
            x=Integer.parseInt(xField.getText());
            y=Integer.parseInt(yField.getText());*/
        
      
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        MyCanvas panel=(MyCanvas)jPanel2;
        Class<? extends Shape> classToLoad=panel.getSupportedShapes().get(panel.supportedShapes.size()-1);
        try{Constructor construct = classToLoad.getConstructor(new Class[]{});
            Method method = classToLoad.getDeclaredMethod("draw",new Class[]{Graphics.class});
            Object instance = construct.newInstance();
            //Object result = method.invoke (instance);
            Shape shape = (Shape)instance ;
            
            panel.addShape(shape);
            this.jLabel3.setText("size"+panel.shapes.size());
            String inputValue = classToLoad.getSimpleName();
            this.jComboBox1.addItem(inputValue+" "+counter++);
            this.jComboBox1.setSelectedIndex(counter-1);
        }catch(Exception e){}
    }//GEN-LAST:event_jButton21ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
       
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
        });
        
        MyCanvas c= new MyCanvas();
        
        //jPanel2.add(c);
        icon = new ImageIcon("/paint/up.png");
        Image img = icon.getImage() ;  
        Image newimg = img.getScaledInstance( 20, 20,  java.awt.Image.SCALE_SMOOTH ) ;  
        icon = new ImageIcon(newimg);
        undoneItems=new ArrayList<>();
        
    }
//public static ArrayList<String> shapeMap=new ArrayList<>();
    public static int counter=0;
    public static ImageIcon icon;
    static ArrayList<String> undoneItems;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
